<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQIJf7MK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQIJf7MK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQIJf7MK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQIJf7MK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQIJf7MK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QIJf7MK',
    'container.build_id' => '5b08fefd',
    'container.build_time' => 1651026774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQIJf7MK');
