<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8xfokjY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8xfokjY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8xfokjY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8xfokjY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8xfokjY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8xfokjY',
    'container.build_id' => '2104b9f9',
    'container.build_time' => 1651623343,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8xfokjY');
