<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpdEyb9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpdEyb9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFpdEyb9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFpdEyb9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFpdEyb9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FpdEyb9',
    'container.build_id' => '423ff360',
    'container.build_time' => 1649936906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpdEyb9');
